### ISSUE TITLE
Commanders require Grandmaster skills instead of Master to learn Abilities

### ISSUE THREAD

**Issue by Warzyw647** [vcmi-mods/wake-of-gods#20]
Commanders require 2 Grandmaster Skills to be offered the respective abilities, for example GM Attack and GM Speed to be offered the ability to shoot on a level-up.
In Era only Master skills are required, not Grandmaster.
Skill descriptions, both in Era and in this vcmi mod also state that Master is the required level.
Tested on vcmi version 1.3.1 with WoG mod version 9.1.1.

**Comment by misiokles** [comment]
I guess it's hardcoded function, can't be fixed in WoG mod. (check config/commanders.json in main vcmi config folder).

**Comment by dydzio0614** [comment]
fixed in https://github.com/vcmi/vcmi/pull/2828
