### ISSUE TITLE
Primary skill icons are not present in all windows

### ISSUE THREAD

**Issue by krs0** [vcmi-mods/wake-of-gods#25]
Missing from:

- [x] Status Window

- [ ] Hero preview window

Current look:
![image](https://github.com/vcmi-mods/wake-of-gods/assets/15194321/3cf7fc43-5fbb-45f3-aea2-03e8e96c3206)

**Comment by IvanSavenko** [comment]
H3 "feature"
You need to replace both "AdStatHr.bmp" and "HEROQVBK.bmp"

**Comment by krs0** [comment]
Ty. Fixed that window too.
